SSH_FOLDER_SOURCE=~/.ssh
SSH_FOLDER_DESTINATION=.devcontainer/home/.ssh
echo 
ls -al .devcontainer/home
echo 
ls -al ~
echo 
if [[ -e $SSH_FOLDER_DESTINATION ]]; then
  rm -rf $SSH_FOLDER_DESTINATION
fi
if [[ ! -e $SSH_FOLDER_DESTINATION ]]; then
  mkdir $SSH_FOLDER_DESTINATION
fi
cp $SSH_FOLDER_SOURCE/* $SSH_FOLDER_DESTINATION
echo -e "${COLOR_LIGHT_GREEN}copied SSH settings from ${COLOR_LIGHT_PURPLE}$SSH_FOLDER_SOURCE${COLOR_LIGHT_GREEN} to ${COLOR_LIGHT_PURPLE}$SSH_FOLDER_DESTINATION${COLOR_NC}"
