SSH_FOLDER_SOURCE="~/.ssh"
SSH_FOLDER_DESTINATION=".devcontainer/home"
rm -rf $SSH_FOLDER_DESTINATION
cp $SSH_FOLDER_SOURCE $SSH_FOLDER_DESTINATION -r
echo -e "${COLOR_LIGHT_GREEN}copied SSH settings from ${COLOR_LIGHT_PURPLE}$SSH_FOLDER_SOURCE${COLOR_LIGHT_GREEN} to ${COLOR_LIGHT_PURPLE}$SSH_FOLDER_DESTINATION${COLOR_NC}"
